@baseUrl = http://localhost:4000

# Get notes
GET {{baseUrl}}/api/notes

###
# Get note
GET {{baseUrl}}/api/notes/6a6a84750683e23cec4d5612

###
# Create note
POST {{baseUrl}}/api/notes
Content-Type: application/json

{
  "content": "Hi",
  "important": true
}

###
# Update note
PUT {{baseUrl}}/api/notes/6a6a84750683e23cec4d5612
Content-Type: application/json

{
  "content": "MongoDB is really God!"
}

###
# Delete note
DELETE {{baseUrl}}/api/notes/6a6bb2b764b2cb650da33fc5

###
# Unknown endpoint
GET {{baseUrl}}/note/info
